# Generated by Django 4.2.9 on 2025-03-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_Market',
            new_name='StockData',
        ),
        migrations.AlterModelOptions(
            name='stockdata',
            options={'verbose_name_plural': 'Stork Data'},
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='trade_code',
            new_name='tradecode',
        ),
    ]
