# Generated by Django 4.2.9 on 2025-03-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_market', '0002_rename_stock_market_stockdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='volume',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
