# Generated by Django 4.2.9 on 2025-03-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_market', '0004_alter_stockdata_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='volume',
            field=models.CharField(max_length=30),
        ),
    ]
