# Generated by Django 4.2.9 on 2025-03-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_market', '0005_alter_stockdata_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='close',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open',
            field=models.CharField(max_length=50),
        ),
    ]
